### ISSUE TITLE
Not able to run examples

### ISSUE THREAD

**Issue by pavan-shipmnts** [alfred82santa/whalesong#110]
I've followed all the instruction using make. I'm getting this
```
pyppeteer.errors.ElementHandleError: Evaluation failed: ReferenceError: webpackJsonp is not defined
```

**Comment by alfred82santa** [comment]
Could you paste all steps you did and results?

**Comment by pavan-shipmnts** [comment]
virtualenv -p python3.7 venv
source venv/bin/activate
pip3 install whalesong
make requirements
make build-js
cd examples
python3.7 presencemonitor-chromium.py
```
(venv) ➜  examples git:(master) ✗ python3 presencemonitor-chromium.py OR python3.7 presencemonitor-chromium.py
Traceback (most recent call last):
  File "presencemonitor-chromium.py", line 108, in <module>
    monitor.loop.run_until_complete(monitor.start())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "presencemonitor-chromium.py", line 94, in start
    await self._driver.start()
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/whalesong/__init__.py", line 96, in start
    await self._driver.connect()
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/whalesong/driver_chromium.py", line 83, in connect
    await self.refresh()
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/whalesong/driver_chromium.py", line 91, in refresh
    await self.run_scriptlet()
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/whalesong/driver.py", line 69, in run_scriptlet
    await self._internal_run_scriptlet(script.read())
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/whalesong/driver_chromium.py", line 95, in _internal_run_scriptlet
    await self.page.evaluate(script)
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/pyppeteer/page.py", line 1158, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/pyppeteer/frame_manager.py", line 295, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/pyppeteer/execution_context.py", line 55, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/Users/pavankumar/Projects/whalesong/venv/lib/python3.7/site-packages/pyppeteer/execution_context.py", line 95, in evaluateHandle
    helper.getExceptionMessage(exceptionDetails)))
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property 'call' of undefined
    at a (https://web.whatsapp.com/progress.78ca5e32cbe8060b40e4.js:2:101)
    at window.webpackJsonp (https://web.whatsapp.com/progress.78ca5e32cbe8060b40e4.js:2:418)
    at createManagers (__pyppeteer_evaluation_script__:1:140290)
    at Object.<anonymous> (__pyppeteer_evaluation_script__:1:163176)
    at __webpack_require__ (__pyppeteer_evaluation_script__:1:128)
    at __pyppeteer_evaluation_script__:1:1200
    at __pyppeteer_evaluation_script__:1:1247
(venv) ➜  examples git:(master) ✗
```
