### ISSUE TITLE
Problem Execute example

### ISSUE THREAD

**Issue by renat473** [alfred82santa/whalesong#112]
Hello,

Problem execute code example.

Traceback (most recent call last):
  File "examples/driver/statemonitor.py", line 5, in <module>
    from whalesong.driver_firefox import WhalesongDriver
  File "/usr/local/lib/python3.5/dist-packages/whalesong/__init__.py", line 4, in <module>
    from .driver import BaseWhalesongDriver
  File "/usr/local/lib/python3.5/dist-packages/whalesong/driver.py", line 22
    self._fut_start: Future = None

**Comment by alfred82santa** [comment]
I guess the problem is that you are using py3.5 that does not recognize variable typing. Try py3.6
