### ISSUE TITLE
Error after executing the minibot.py

### ISSUE THREAD

**Issue by jersonjunior** [alfred82santa/whalesong#114]
python3 minibot.py 
Traceback (most recent call last):
  File "minibot.py", line 238, in <module>
    bot.loop.run_until_complete(bot.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "minibot.py", line 225, in start
    await self._driver.start()
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/whalesong/__init__.py", line 96, in start
    await self._driver.connect()
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 108, in connect
    await self.run_scriptlet()
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/whalesong/driver.py", line 69, in run_scriptlet
    await self._internal_run_scriptlet(script.read())
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 119, in _internal_run_scriptlet
    await self._run_async(self.driver.execute_script, script)
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 73, in _run_async
    return await self.loop.run_in_executor(self._pool_executor, partial(method, *args, **kwargs))
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jersonjunior/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: e[o] is undefined

**Comment by gladimaz** [comment]
#109

**Comment by jersonjunior** [comment]
I performed the issue command that you mentioned but whalesong continues in the version  0.9.0.

**Comment by jersonjunior** [comment]
Solved using PYTHONPATH=.:$PYTHONPATH python3 examples/statemonitor.py
