### ISSUE TITLE
Message: Service geckodriver unexpectedly exited. Status code was: -11

### ISSUE THREAD

**Issue by edwinalex035** [alfred82santa/whalesong#118]
Hi, we are using the whaleshong 0.9.0 for firefox. The installed firefox version 68.0.2, but when we try to start the python script we receive the following error:
Traceback (most recent call last):
  File "/root/webwhatsappinterface/worker/webWhatsappinterface_python3.py", line 737, in <module>
    bot.loop.run_until_complete(bot.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/root/webwhatsappinterface/worker/webWhatsappinterface_python3.py", line 703, in start
    await self._driver.start()
  File "/usr/local/lib/python3.6/dist-packages/whalesong/__init__.py", line 95, in start
    await self._driver.start_driver()
  File "/usr/local/lib/python3.6/dist-packages/whalesong/driver.py", line 49, in start_driver
    await self._fut_start
  File "/usr/local/lib/python3.6/dist-packages/whalesong/driver.py", line 53, in start_driver
    await self._fut_start
  File "/usr/local/lib/python3.6/dist-packages/whalesong/driver_firefox.py", line 76, in _internal_start_driver
    self.driver = await self._run_async(self._internal_start_driver_sync)
  File "/usr/local/lib/python3.6/dist-packages/whalesong/driver_firefox.py", line 73, in _run_async
    return await self.loop.run_in_executor(self._pool_executor, partial(method, *args, **kwargs))
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/whalesong/driver_firefox.py", line 98, in _internal_start_driver_sync
    **self.options['extra_params'])
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -11

**Comment by alfred82santa** [comment]
It looks like a problem with Selenium version and firefox versio: https://stackoverflow.com/questions/54014683/selenium-with-firefox-webdriver-results-in-error-service-geckodriver-unexpected
