### ISSUE TITLE
 exception=ManagerNotFound('Manager messages not found'

### ISSUE THREAD

**Issue by yoeliguzman** [alfred82santa/whalesong#122]
Now we this issue when application load; none new message can be sent, please your kindly help i am in a urgency: thanks in advanced

2019-09-30 17:19:53,236 ERROR    Task exception was never retrieved
future: <Task finished coro=<Minibot.monitor_new_messages() done, defined at /root/webwhatsappinterface/worker/webWhatsappinterface_python3.py:270> exception=ManagerNotFound('Manager messages not found',)>
Traceback (most recent call last):
  File "/root/webwhatsappinterface/worker/webWhatsappinterface_python3.py", line 276, in monitor_new_messages
    async for message in it:
  File "/usr/local/lib/python3.6/dist-packages/whalesong/results.py", line 195, in __anext__
    evt: T = await super(MonitorResult, self).__anext__()
  File "/usr/local/lib/python3.6/dist-packages/whalesong/results.py", line 137, in __anext__
    raise item
whalesong.errors.ManagerNotFound: Manager messages not found
2019-09-30 17:19:53,237 ERROR    Task exception was never retrieved
future: <Task finished coro=<Minibot.monitor_message_acks() done, defined at /root/webwhatsappinterface/worker/webWhatsappinterface_python3.py:103> exception=ManagerNotFound('Manager messages not found',)>
Traceback (most recent call last):
  File "/root/webwhatsappinterface/worker/webWhatsappinterface_python3.py", line 105, in monitor_message_acks
    async for ack in it:
  File "/usr/local/lib/python3.6/dist-packages/whalesong/results.py", line 195, in __anext__
    evt: T = await super(MonitorResult, self).__anext__()
  File "/usr/local/lib/python3.6/dist-packages/whalesong/results.py", line 137, in __anext__
    raise item
whalesong.errors.ManagerNotFound: Manager messages not found

**Comment by vasani-arpit** [comment]
Please have a look at https://github.com/alfred82santa/whalesong/issues/121#issuecomment-536587381

**Comment by yoeliguzman** [comment]
Thanks @vasani-arpit

**Comment by vasani-arpit** [comment]
@alfred82santa, You may close this one.
