### ISSUE TITLE
error on chromium

### ISSUE THREAD

**Issue by varbdev** [alfred82santa/whalesong#123]
pyppeteer.errors.ElementHandleError: Evaluation failed: ReferenceError: webpackJsonp is not defined

**Comment by vasani-arpit** [comment]
Please provider the steps to reproduce and explanation for the error.

**Comment by varbdev** [comment]
[root@vps180388 whalesong]# PYTHONPATH=.:$PYTHONPATH python3 examples/minibot-chromium.py 
Traceback (most recent call last):
  File "examples/minibot-chromium.py", line 240, in <module>
    bot.loop.run_until_complete(bot.start())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "examples/minibot-chromium.py", line 227, in start
    await self._driver.start()
  File "/home/whatsapp/whalesong/whalesong/__init__.py", line 96, in start
    await self._driver.connect()
  File "/home/whatsapp/whalesong/whalesong/driver_chromium.py", line 83, in connect
    await self.refresh()
  File "/home/whatsapp/whalesong/whalesong/driver_chromium.py", line 91, in refresh
    await self.run_scriptlet()
  File "/home/whatsapp/whalesong/whalesong/driver.py", line 69, in run_scriptlet
    await self._internal_run_scriptlet(script.read())
  File "/home/whatsapp/whalesong/whalesong/driver_chromium.py", line 95, in _internal_run_scriptlet
    await self.page.evaluate(script)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/page.py", line 1158, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/frame_manager.py", line 295, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 55, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 95, in evaluateHandle
    helper.getExceptionMessage(exceptionDetails)))
pyppeteer.errors.ElementHandleError: Evaluation failed: ReferenceError: webpackJsonp is not defined
    at createManagers (__pyppeteer_evaluation_script__:1:130627)
    at Object.<anonymous> (__pyppeteer_evaluation_script__:1:102948)
    at __webpack_require__ (__pyppeteer_evaluation_script__:1:128)
    at __pyppeteer_evaluation_script__:1:1200
    at __pyppeteer_evaluation_script__:1:1246
