### ISSUE TITLE
Can't Retrieve QR Code

### ISSUE THREAD

**Issue by seanmostafavi** [alfred82santa/whalesong#59]
I used to be able to retrieve an auth QR code via the Firefox driver using qr() or screenshot_element("div[data-ref]") but that's no longer the case.  I suspect WhatsApp changed their page layout and the CSS query selector "div[data-ref]" doesn't seem to work anymore.

**Comment by alfred82santa** [comment]
I've tested it right now and it works. It is possible you are get a new version from WhatsappWeb that I don't get.

Could you post a screenshot of html tree around image? (using Firefox inspector)

**Comment by seanmostafavi** [comment]
Thank you for the quick response!  Here's a screenshot where "loadstyles" is set to True (I've tried setting that to False as well and run into the same issue).
![image](https://user-images.githubusercontent.com/16457621/51716330-4400e700-1ff1-11e9-8c9b-5a8926b90caa.png)

**Comment by alfred82santa** [comment]
![imatge](https://user-images.githubusercontent.com/574291/51735017-83c5de00-2086-11e9-8f59-276ca33a1113.png)

It should work. Maybe it is another problem: #60

**Comment by seanmostafavi** [comment]
I was crossing my fingers, wishing the latest Whalesong release (0.8.1) would fix this issue but it does not.  For the record, I encounter the QR issue on Mac OS Mojave while accessing WhatsApp in North America, west coast.  I'm going to try it out on Linux and hopefully it works there.  I believe this is a known issue but qr() doesn't work on Chromium for me either.  Let me know if there's anything else you think I can try.  Thank you for all your work!  Cheers.

**Comment by alfred82santa** [comment]
Any news?

**Comment by Tingaev** [comment]
I just get screenshot all window. I didn't get screenshot only qr code

**Comment by alfred82santa** [comment]
Which error does it raise when you try to get QR?

**Comment by Tingaev** [comment]
`Message: Unable to locate element: div[data-ref]

Error getting qr`

**Comment by alfred82santa** [comment]
Could you capture exception and make a screenshot?

something like this:

```python3

try:
     image = await self._driver.get_qr()
except Exception:
     image = await self._driver.screenshot()
```

**Comment by Tingaev** [comment]
```
            try:
                img2 = await self._driver.screenshot()
                with open(path.join(self.OUTPUT_DIR, 'qr_{}.png'.format(self.bot_id)), 'wb') as f:
                    f.write(img2.read())
                self.echo('QR saved!')
                img = await self._driver.qr()
                with open(path.join(self.OUTPUT_DIR, 'qr_{}.png'.format(self.bot_id)), 'wb') as f:
                    f.write(img.read())
                self.echo('QR saved!')
            except Exception as ex:
                self.echo(ex)
                self.echo('Error getting qr')
```

**Comment by alfred82santa** [comment]
ok, could you post the screenshot?

**Comment by Tingaev** [comment]
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/40757170/52232519-90480300-28de-11e9-8cd9-92fee3815193.png">

**Comment by alfred82santa** [comment]
Well, definitely it is there.

Which versions of firefox and selenium are you using?

**Comment by Tingaev** [comment]
firefox 65.0 x64
selenium 3.141.0

**Comment by Tingaev** [comment]
I install selenium 3.4.3 and get this traceback
```
Task exception was never retrieved
future: <Task finished coro=<BaseWhalesongDriver.start_driver() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver.py:40> exception=TypeError("__init__() got an unexpected keyword argument 'options'",)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver.py", line 49, in start_driver
    await self._fut_start
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 63, in _internal_start_driver
    self.driver = await self._run_async(self._internal_start_driver_sync)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 60, in _run_async
    return await self.loop.run_in_executor(self._pool_executor, partial(method, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 83, in _internal_start_driver_sync
    **self.options['extra_params'])
TypeError: __init__() got an unexpected keyword argument 'options'
Traceback (most recent call last):
  File "minibot.py", line 333, in <module>
    bot.loop.run_until_complete(bot.start())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "minibot.py", line 312, in start
    await self._driver.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/__init__.py", line 94, in start
    await self._driver.start_driver()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver.py", line 45, in start_driver
    await self._fut_start
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver.py", line 49, in start_driver
    await self._fut_start
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 63, in _internal_start_driver
    self.driver = await self._run_async(self._internal_start_driver_sync)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 60, in _run_async
    return await self.loop.run_in_executor(self._pool_executor, partial(method, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 83, in _internal_start_driver_sync
    **self.options['extra_params'])
TypeError: __init__() got an unexpected keyword argument 'options'
```

**Comment by alfred82santa** [comment]
I found the problem. It is not about firefox or selenium. It is in whalesong firefox driver.

**Comment by alfred82santa** [comment]
Could you test now?

**Comment by Tingaev** [comment]
Thank you very much, it works🙂

**Comment by seanmostafavi** [comment]
Thank you, it works like a charm now!
