### ISSUE TITLE
ERROR INSTALL HELP !!

### ISSUE THREAD

**Issue by Theblood** [alfred82santa/whalesong#67]
ERROR in ./src/index.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/home/srvws/whalesong/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/srvws/whalesong/node_modules/babel-loader/lib/index.js:10:11)
    at Module._compile (/home/srvws/whalesong/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/srvws/whalesong/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadLoader (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:18:17)
    at iteratePitchingLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/usr/lib/node_modules/webpack/lib/NormalModule.js:280:3)
    at NormalModule.build (/usr/lib/node_modules/webpack/lib/NormalModule.js:427:15)
    at Compilation.buildModule (/usr/lib/node_modules/webpack/lib/Compilation.js:635:10)
    at moduleFactory.create (/usr/lib/node_modules/webpack/lib/Compilation.js:1021:12)
    at factory (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/usr/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at resolver (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
    at process.nextTick (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by alfred82santa** [comment]
Have you followed instructions?

https://github.com/alfred82santa/whalesong#getting-started

**Comment by Theblood** [comment]
@alfred82santa   Hello, great the project has been testing it, create a request configuring the correct version of python pip3.  #68

**Comment by alfred82santa** [comment]
Well, I've approved your PR, but it wasn't about your problem with node. Have you you solved it?

**Comment by Theblood** [comment]
Yes, I love this, I want to contribute more for what I hope I can do more PR @alfred82santa
