### ISSUE TITLE
Bug on real time location

### ISSUE THREAD

**Issue by jesusvalverde** [alfred82santa/whalesong#73]
If you use actual location (mi ubicación actual in Spanish) all goes OK....BUT if you use "on real time" (en tiempo real) you get this..

year 49122572 is out of range
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/managers/message.py", line 101, in __call__
    return cls.__message_classes__[t](data=data, *args, **kwargs)
KeyError: 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 149, in poll
    await self.result_manager.set_partial_result(result['exId'], result['params'])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/results.py", line 280, in set_partial_result
    await cast(BasePartialResult, self._pendant[result_id]).set_partial_result(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/results.py", line 115, in set_partial_result
    await self._set_result(self.map(data))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/results.py", line 47, in map
    return self.fn_map(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/managers/__init__.py", line 161, in <lambda>
    fn_map=lambda evt: cls.MODEL_MANAGER_CLASS.map_model(evt['item'])))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/managers/__init__.py", line 93, in map_model
    return cls.MODEL_CLASS(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/managers/message.py", line 104, in __call__
    return cls.__message_classes__[MessageTypes(t)](data=data, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/whalesong/managers/message.py", line 90, in __call__
    return super(MessageMetaclass, cls).__call__(data=data, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/models.py", line 182, in __init__
    self.import_data(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/models.py", line 301, in import_data
    self._import_data(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/models.py", line 308, in _import_data
    setattr(self, key, value)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/fields.py", line 116, in __set__
    set_value(value)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/fields.py", line 112, in set_value
    self.set_value(obj, self.use_value(v))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/fields.py", line 58, in use_value
    return self.convert_value(value)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/fields.py", line 152, in inner
    return func(self, value)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/dirty_models/fields.py", line 567, in convert_value
    return datetime.fromtimestamp(value, tz=self.default_timezone)
ValueError: year 49122572 is out of range

Found the error is over   ""sequence = DateTimeField()"" on the 505 lines message.py file, buy as long I dont know what else afect this line I wont make upload the file.

**Comment by alfred82santa** [comment]
Could you test it?

**Comment by jesusvalverde** [comment]
Working Fine !!!
